// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fill_array_impl
void fill_array_impl(SEXP output, List chunks, List out_offsets, List ic_offsets, IntegerMatrix copy_lengths, IntegerVector out_dims, IntegerVector ic_dims);
RcppExport SEXP _zarr_fill_array_impl(SEXP outputSEXP, SEXP chunksSEXP, SEXP out_offsetsSEXP, SEXP ic_offsetsSEXP, SEXP copy_lengthsSEXP, SEXP out_dimsSEXP, SEXP ic_dimsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type output(outputSEXP);
    Rcpp::traits::input_parameter< List >::type chunks(chunksSEXP);
    Rcpp::traits::input_parameter< List >::type out_offsets(out_offsetsSEXP);
    Rcpp::traits::input_parameter< List >::type ic_offsets(ic_offsetsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type copy_lengths(copy_lengthsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type out_dims(out_dimsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ic_dims(ic_dimsSEXP);
    fill_array_impl(output, chunks, out_offsets, ic_offsets, copy_lengths, out_dims, ic_dims);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_zarr_fill_array_impl", (DL_FUNC) &_zarr_fill_array_impl, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_zarr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
