# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fill regions of an output array from a list of inner chunk arrays
#'
#' This function fills `output` in place. For each inner chunk, it copies
#' elements from the decoded chunk into the correct position in the output
#' array. All index arithmetic is done in C++ to avoid R-level copying and
#' garbage collection pressure.
#'
#' @param output A numeric/integer/raw vector with dim attribute set — the
#'   output array to fill. Modified in place via SEXP reference.
#' @param chunks List of decoded inner chunk arrays (already in R order).
#' @param out_offsets List of integer vectors, one per chunk, giving the
#'   0-based offset of that chunk's contribution within `output`.
#' @param ic_offsets List of integer vectors, one per chunk, giving the
#'   0-based offset within the inner chunk to start copying from.
#' @param copy_lengths Integer matrix \code{[nd x n_chunks]} of element counts
#'   to copy along each dimension.
#' @param out_dims Integer vector of output array dimensions.
#' @param ic_dims Integer vector of inner chunk dimensions.
#' @return NULL invisibly; `output` is modified in place.
#' @keywords internal
fill_array_impl <- function(output, chunks, out_offsets, ic_offsets, copy_lengths, out_dims, ic_dims) {
    invisible(.Call(`_zarr_fill_array_impl`, output, chunks, out_offsets, ic_offsets, copy_lengths, out_dims, ic_dims))
}

